### ISSUE TITLE
textures don't load

### ISSUE THREAD

**Issue by Not-AriStienfeld** [yanes19/SU-27SK#4]
the textures don't load, it is just the blue/yellow default untextured plane. no cockpit view, pressing any of the options under the su-27/j11a menu do nothing. obviously cockpit view doesn't work. engines, gear, and turning works though.

**Comment by yanes19** [comment]
Hi and thanks for your interest , 
The behavior you described is so strange that I cant reproduce and never reported by others ,
it looks like the -set.xml file itself is either not intact (corrupted file ) or not correctly loaded ,
it would be great to mention the FG version and the OS you are using ,
please make sure you download/clone the package properly and try with the Su-27SK as it's the main variant and is ahead of the 
j-11 by several steps ,

**Comment by sidi762** [comment]
Did you renamed the folder and removed the -master?

**Comment by Not-AriStienfeld** [comment]
It works now, I’m not sure why

From,
Ari Steinfeld

**Comment by sidi762** [comment]
That's a good news!
